/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultsIndexRouteImport } from './routes/results.index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as AlertsIndexRouteImport } from './routes/alerts/index'
import { Route as AlertsLoginRouteImport } from './routes/alerts/login'
import { Route as AlertsEditRouteImport } from './routes/alerts/edit'
import { Route as AlertsCallbackRouteImport } from './routes/alerts/callback'

const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIndexRoute = ResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsLoginRoute = AlertsLoginRouteImport.update({
  id: '/alerts/login',
  path: '/alerts/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsEditRoute = AlertsEditRouteImport.update({
  id: '/alerts/edit',
  path: '/alerts/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsCallbackRoute = AlertsCallbackRouteImport.update({
  id: '/alerts/callback',
  path: '/alerts/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/alerts/callback': typeof AlertsCallbackRoute
  '/alerts/edit': typeof AlertsEditRoute
  '/alerts/login': typeof AlertsLoginRoute
  '/alerts/': typeof AlertsIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/results/': typeof ResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/alerts/callback': typeof AlertsCallbackRoute
  '/alerts/edit': typeof AlertsEditRoute
  '/alerts/login': typeof AlertsLoginRoute
  '/alerts': typeof AlertsIndexRoute
  '/docs': typeof DocsIndexRoute
  '/results': typeof ResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/alerts/callback': typeof AlertsCallbackRoute
  '/alerts/edit': typeof AlertsEditRoute
  '/alerts/login': typeof AlertsLoginRoute
  '/alerts/': typeof AlertsIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/results/': typeof ResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/alerts/callback'
    | '/alerts/edit'
    | '/alerts/login'
    | '/alerts/'
    | '/docs/'
    | '/results/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/alerts/callback'
    | '/alerts/edit'
    | '/alerts/login'
    | '/alerts'
    | '/docs'
    | '/results'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/alerts/callback'
    | '/alerts/edit'
    | '/alerts/login'
    | '/alerts/'
    | '/docs/'
    | '/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AlertsCallbackRoute: typeof AlertsCallbackRoute
  AlertsEditRoute: typeof AlertsEditRoute
  AlertsLoginRoute: typeof AlertsLoginRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ResultsIndexRoute: typeof ResultsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/': {
      id: '/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof ResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/login': {
      id: '/alerts/login'
      path: '/alerts/login'
      fullPath: '/alerts/login'
      preLoaderRoute: typeof AlertsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/edit': {
      id: '/alerts/edit'
      path: '/alerts/edit'
      fullPath: '/alerts/edit'
      preLoaderRoute: typeof AlertsEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/callback': {
      id: '/alerts/callback'
      path: '/alerts/callback'
      fullPath: '/alerts/callback'
      preLoaderRoute: typeof AlertsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AlertsCallbackRoute: AlertsCallbackRoute,
  AlertsEditRoute: AlertsEditRoute,
  AlertsLoginRoute: AlertsLoginRoute,
  AlertsIndexRoute: AlertsIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  ResultsIndexRoute: ResultsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
